
opt_in_rules:
  - closure_spacing
  - force_unwrapping
  - private_unit_test
  - overridden_super_call
  - redundant_nil_coalescing
  - attributes
  - empty_parameters
  - explicit_init
  - first_where
  - operator_usage_whitespace
  - prohibited_super_call
  - empty_count
  - fatal_error_message
  - conditional_returns_on_newline
  - explicit_top_level_acl
  - implicitly_unwrapped_optional
  - object_literal
  - private_outlet
  - switch_case_on_newline
  - array_init
  - contains_over_first_not_nil
  - empty_string
  - implicit_return
  - joined_default_parameter
  - unneeded_parentheses_in_closure_argument
  
disabled_rules:
  - large_tuple
  - identifier_name # does not work in Xcode 10 beta

excluded:
  - Carthage
  - tdjson
  - TDLib/Generated
  - vendor
  - bundle
  - fastlane

identifier_name:
  min_length:
    warning: 2
  excluded:
    - id
    - x
    - y
allExceptIBOutlets:
  mode: all
trailing_whitespace:
  ignores_empty_lines: true
line_length:
  ignores_comments: true
  warning: 150
  error: 300
nesting:
  type_level:
    warning: 5
type_name:
  excluded:
    - Ok